name: ex3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.10
  - numpy==1.18.1
  - scipy==1.4.1
  - pytorch==1.4.0
  - gym==0.19.0
  - conda-forge::stable-baselines3
  - scikit-learn==0.22.1
  - tensorflow==1.15.0
  - mpi4py==3.0.3
  - emcee
  - gcc=12.1.0
